-- PaperPath — every migration after schema.sql, in one file.
--
-- GENERATED by scripts/build-migration.ts. Do not edit: edit the source files
-- and regenerate, or the two will disagree and nobody will be able to tell
-- which one is running on the database.
--
-- RUN supabase/schema.sql FIRST if you have not. This assumes profiles,
-- attempts and ai_usage already exist.
--
-- cron.sql is NOT here: it schedules against a URL and a secret you have to
-- fill in by hand, and a scheduler pointing at REPLACE-ME looks configured.
--
-- Order below is dependency order, not alphabetical:
--   tutor.sql        needs schema.sql — adds columns to its `attempts` table
--   compliance.sql   needs schema.sql for profiles, tutor.sql for the retention job's tables
--   schools.sql      needs tutor.sql for topics and topic_mastery
--   billing.sql      needs schools.sql — can_access_chapter reads org_members
--   ratelimit.sql    needs nothing, but compliance.sql's purge calls into it
--   analytics.sql    needs tutor.sql for llm_calls and error_events
--   tenancy.sql      needs schools.sql (extends org_members) and billing.sql (replaces can_access_chapter) — LAST, because it rewrites what came before



-- ===========================================================================
-- tutor.sql
-- ===========================================================================

-- PaperPath — the tutoring layer
--
-- Run this AFTER supabase/schema.sql. It adds two things that file does not
-- have: a seeded curriculum, and the runtime state of a teaching session.
--
-- ---------------------------------------------------------------------------
-- WHY A SEEDED CURRICULUM AND NOT MORE GENERATION
--
-- Everything in schema.sql is generated per student: the model writes the
-- questions, marks them, and writes the notes. That works for revision, where
-- the student already knows the material and wants volume.
--
-- Teaching is a different job. A tutor that invents its own explanation each
-- time cannot be checked, cannot be corrected once, and drifts off the board's
-- syllabus in ways nobody notices until a parent does. So the teaching content
-- is written once, by hand, and stored here. The model's job shrinks to
-- delivering material it did not choose — which is the part it is reliably
-- good at.
--
-- The tables below are therefore of two kinds, with opposite access rules:
--
--   CURRICULUM  subjects, chapters, topics, concepts, bank_questions.
--               Global, not per-student. Written by the seed script running
--               with the service-role key. Students read the teaching content;
--               they must never read the answers.
--
--   RUNTIME     learning_sessions, session_turns, error_events, topic_mastery,
--               llm_calls, credit_ledger. Per-student, row-level secured
--               exactly like the rest of the app.
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- CURRICULUM
-- ===========================================================================

-- Ids are slugs, not sequences ('cbse-8-maths-ch1-t2-c1'). The content lives in
-- JSON files under content/ and is pushed by scripts/seed-content.mjs; a stable
-- textual id makes that push idempotent and makes a diff of the seed readable.

create table if not exists public.subjects (
  id          text primary key,
  board       text not null,                 -- cbse | icse | upboard
  class_level int  not null,
  subject_id  text not null,                 -- maths | science | ... (lib/syllabus.ts)
  name        text not null,
  language    text not null default 'en-IN',
  unique (board, class_level, subject_id, language)
);

create table if not exists public.chapters (
  id          text primary key,
  subject_ref text not null references public.subjects on delete cascade,
  chapter_no  int  not null,
  title       text not null,
  ncert_ref   text,
  est_minutes int  not null default 45,
  -- The first chapter of a subject is free. It is the only honest way to let a
  -- parent judge the teaching before paying for it.
  is_free     boolean not null default false,
  unique (subject_ref, chapter_no)
);

create table if not exists public.topics (
  id               text primary key,
  chapter_ref      text not null references public.chapters on delete cascade,
  topic_no         int  not null,
  title            text not null,
  -- Unlock gating. A topic opens when every id listed here has a mastery score
  -- of at least 60. Empty means it is open from the start.
  prereq_topic_ids text[] not null default '{}',
  unique (chapter_ref, topic_no)
);

-- The most important table in the database.
--
-- `misconceptions` is the column that earns its keep. Handed the list, the
-- model probes for mistakes we already know Class 8 students make; left to
-- find them itself it invents plausible ones, and a tutor chasing an imagined
-- error is worse than one that stays quiet.
create table if not exists public.concepts (
  id              text primary key,
  topic_ref       text not null references public.topics on delete cascade,
  seq             int  not null,
  title           text not null,
  statement       text not null,
  hook            text,
  analogies       jsonb not null default '[]'::jsonb,
  -- [{id, wrong_belief, why_wrong, correction, probe}]
  misconceptions  jsonb not null default '[]'::jsonb,
  -- [{id, problem, steps[], answer}]
  worked_examples jsonb not null default '[]'::jsonb,
  -- [{id, latex, note}]
  formulas        jsonb not null default '[]'::jsonb,
  unique (topic_ref, seq)
);

-- Named bank_questions, not questions: generated_questions already exists and
-- holds a completely different thing (per-student, model-written, discarded
-- after marking). Two tables called some flavour of "questions" is how the
-- wrong one gets joined at 2am.
create table if not exists public.bank_questions (
  id             text primary key,
  topic_ref      text not null references public.topics on delete cascade,
  concept_ref    text references public.concepts on delete set null,
  qtype          text not null check (qtype in ('mcq', 'msq', 'nvt', 'subjective')),
  level          text not null check (level in ('L1', 'L2', 'L3', 'L4')),
  stem           text not null,               -- LaTeX between $...$
  options        jsonb,                       -- [{key, text}]
  correct        jsonb not null,              -- ["A"] | {value, tol} | {rubric[]}
  solution       text not null,
  -- {"B": "m1"} — every wrong option mapped to the misconception it comes from.
  --
  -- This is what makes most marking free. When a student picks B we know which
  -- wrong belief produced it without asking a model, which means the diagnosis
  -- costs nothing, arrives instantly, and is right every time. The model is
  -- only needed for the subjective questions.
  distractor_map jsonb not null default '{}'::jsonb,
  marks          numeric(4,2) not null default 4,
  negative_marks numeric(4,2) not null default 1,
  source         text
);

create index if not exists bank_questions_topic_level_idx
  on public.bank_questions (topic_ref, level);

create index if not exists bank_questions_concept_idx
  on public.bank_questions (concept_ref);

-- --- Curriculum access -----------------------------------------------------
--
-- Teaching content is readable by any signed-in student. Answers are not
-- readable by anyone through the API at all.

alter table public.subjects       enable row level security;
alter table public.chapters       enable row level security;
alter table public.topics         enable row level security;
alter table public.concepts       enable row level security;
alter table public.bank_questions enable row level security;

drop policy if exists "subjects are readable" on public.subjects;
create policy "subjects are readable" on public.subjects
  for select to authenticated using (true);

drop policy if exists "chapters are readable" on public.chapters;
create policy "chapters are readable" on public.chapters
  for select to authenticated using (true);

drop policy if exists "topics are readable" on public.topics;
create policy "topics are readable" on public.topics
  for select to authenticated using (true);

drop policy if exists "concepts are readable" on public.concepts;
create policy "concepts are readable" on public.concepts
  for select to authenticated using (true);

-- bank_questions deliberately has NO select policy. With RLS on and no policy,
-- PostgREST returns nothing to a signed-in student however they ask — which is
-- the point. A student who opens DevTools on the practice screen finds the
-- stem and the options and nothing else.
--
-- Server routes reach the answers through the service-role key
-- (lib/supabase/admin.ts), which bypasses RLS and never reaches the browser.
--
-- There was a `bank_question_prompts` view here, exposing every column except
-- the answers so a browser could read questions directly. It is dropped, and
-- the reasoning is worth keeping:
--
--   Nothing used it. Every question the app serves goes through
--   /api/tutor/practice/next, which reads with the service-role key and
--   chooses its columns explicitly. The view was a second, unused path to the
--   same table whose safety rested on a subtlety — that a view runs as its
--   owner and therefore bypasses the RLS on what it selects.
--
--   That subtlety is exactly the kind that stops being true. A future
--   Postgres default, a changed owner, or someone adding `security_invoker` to
--   tidy things up, and a table whose whole design is "no client may read this"
--   quietly becomes readable. A door nobody walks through is still a door.
--
-- If a direct client read is ever wanted, add it back deliberately and write a
-- test that asserts an anon key cannot select `correct` through it.
drop view if exists public.bank_question_prompts;

-- ===========================================================================
-- RUNTIME
-- ===========================================================================

-- --- Sessions --------------------------------------------------------------
--
-- current_beat is written by the server and only by the server. The model
-- reports whether the student understood; it does not get to decide what
-- happens next. Keeping the transition here is what stops a session from
-- looping forever or skipping the check when the model feels agreeable.

create table if not exists public.learning_sessions (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users on delete cascade,
  topic_ref     text not null references public.topics on delete cascade,
  concept_ref   text not null references public.concepts on delete cascade,
  current_beat  text not null default 'HOOK'
                check (current_beat in ('HOOK','TEACH','CHECK','RETEACH','SUMMARY','DONE')),
  turns_used    int  not null default 0,
  reteach_count int  not null default 0,
  status        text not null default 'active'
                check (status in ('active', 'paused', 'completed')),
  started_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists learning_sessions_user_idx
  on public.learning_sessions (user_id, started_at desc);

create table if not exists public.session_turns (
  id         uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.learning_sessions on delete cascade,
  -- Denormalised so the row-level policy is one comparison rather than a join
  -- on every insert of every turn.
  user_id    uuid not null references auth.users on delete cascade,
  seq        int  not null,
  beat       text not null,
  role       text not null check (role in ('tutor', 'student')),
  content    text not null,
  verdict    jsonb,
  provider   text,
  model      text,
  tokens_in  int,
  tokens_out int,
  latency_ms int,
  created_at timestamptz not null default now(),
  unique (session_id, seq)
);

alter table public.learning_sessions enable row level security;
alter table public.session_turns     enable row level security;

drop policy if exists "sessions are self-service" on public.learning_sessions;
create policy "sessions are self-service" on public.learning_sessions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "session turns are self-service" on public.session_turns;
create policy "session turns are self-service" on public.session_turns
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- --- Attempts against the bank ---------------------------------------------
--
-- schema.sql already has `attempts`, keyed to generated_questions. A second
-- attempts table would split the readiness score across two places, so the
-- bank's columns are added to the existing one instead.

alter table public.attempts
  add column if not exists topic_ref text references public.topics on delete set null;
alter table public.attempts
  add column if not exists concept_ref text references public.concepts on delete set null;
alter table public.attempts
  add column if not exists bank_question_id text references public.bank_questions on delete set null;
alter table public.attempts
  add column if not exists session_id uuid references public.learning_sessions on delete set null;
alter table public.attempts
  add column if not exists answer jsonb;
alter table public.attempts
  add column if not exists time_taken_ms int;

create index if not exists attempts_user_topic_idx
  on public.attempts (user_id, topic_ref, created_at desc);

-- --- Error events ----------------------------------------------------------
--
-- One row per diagnosed mistake. `source` is the column to watch in production:
-- if 'llm' is more than a small minority of rows, the distractor maps are too
-- thin and the fix is more content, not a better model.

create table if not exists public.error_events (
  id          uuid primary key default gen_random_uuid(),
  attempt_id  uuid references public.attempts on delete cascade,
  user_id     uuid not null references auth.users on delete cascade,
  topic_ref   text references public.topics on delete set null,
  concept_ref text references public.concepts on delete set null,
  -- The taxonomy in lib/mastery.ts, unchanged:
  -- concept | formula | application | calculation | careless | incomplete |
  -- blank | guess
  etype           text not null,
  misconception_id text,
  confidence      numeric(3,2),
  evidence        text,
  source          text not null check (source in ('distractor_map', 'rule', 'llm')),
  created_at      timestamptz not null default now()
);

create index if not exists error_events_user_type_idx
  on public.error_events (user_id, etype, created_at desc);

create index if not exists error_events_user_concept_idx
  on public.error_events (user_id, concept_ref, created_at desc);

alter table public.error_events enable row level security;

drop policy if exists "error events are self-service" on public.error_events;
create policy "error events are self-service" on public.error_events
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- --- Mastery and spaced repetition -----------------------------------------
--
-- Bands use the vocabulary already in lib/mastery.ts rather than a second set,
-- so the tutor and the revision side of the app describe a student the same
-- way.

create table if not exists public.topic_mastery (
  user_id       uuid not null references auth.users on delete cascade,
  topic_ref     text not null references public.topics on delete cascade,
  teach_done    boolean not null default false,
  practice_acc  numeric(5,2) not null default 0,
  test_score    numeric(5,2),
  score         numeric(5,2) not null default 0,
  band          text not null default 'Not started',
  -- SM-2
  ease_factor   numeric(4,2) not null default 2.5,
  interval_days int not null default 0,
  next_review_at date,
  updated_at    timestamptz not null default now(),
  primary key (user_id, topic_ref)
);

create index if not exists topic_mastery_due_idx
  on public.topic_mastery (user_id, next_review_at);

alter table public.topic_mastery enable row level security;

drop policy if exists "mastery is self-service" on public.topic_mastery;
create policy "mastery is self-service" on public.topic_mastery
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- --- Parent links ----------------------------------------------------------
--
-- In this market the parent pays and the student uses. A product with nothing
-- for the parent renews badly.
--
-- The link is deliberately not a read grant on the student's tables: the
-- report route checks this table and then reads through the service-role key,
-- so a parent gets the weekly digest and never gets a session transcript.

create table if not exists public.parent_links (
  parent_id  uuid not null references auth.users on delete cascade,
  student_id uuid not null references auth.users on delete cascade,
  relation   text not null default 'parent',
  -- The student's account confirms the link. Without this a phone number typo
  -- sends one family's report to another.
  confirmed  boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (parent_id, student_id)
);

alter table public.parent_links enable row level security;

drop policy if exists "parent links are visible to both sides" on public.parent_links;
create policy "parent links are visible to both sides" on public.parent_links
  for select using (auth.uid() = parent_id or auth.uid() = student_id);

drop policy if exists "a parent may request a link" on public.parent_links;
create policy "a parent may request a link" on public.parent_links
  for insert with check (auth.uid() = parent_id);

drop policy if exists "a student may confirm a link" on public.parent_links;
create policy "a student may confirm a link" on public.parent_links
  for update using (auth.uid() = student_id) with check (auth.uid() = student_id);

-- --- Unit economics --------------------------------------------------------
--
-- Put in on day one, not when the bill arrives. Without a per-call row there
-- is no way to answer "what does one taught concept cost" — and that number
-- decides whether the subscription price works.

create table if not exists public.llm_calls (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid references auth.users on delete set null,
  session_id uuid references public.learning_sessions on delete set null,
  purpose    text not null,              -- teach | check | classify | solve | summary
  provider   text not null,
  model      text not null,
  tokens_in  int not null default 0,
  tokens_out int not null default 0,
  cost_inr   numeric(10,4),
  latency_ms int,
  -- True when the primary provider failed and the fallback served the call.
  fell_back  boolean not null default false,
  ok         boolean not null default true,
  error      text,
  created_at timestamptz not null default now()
);

create index if not exists llm_calls_created_idx on public.llm_calls (created_at desc);
create index if not exists llm_calls_user_idx on public.llm_calls (user_id, created_at desc);

alter table public.llm_calls enable row level security;

-- Written by the server with the service-role key. A student may read their own
-- spend and may not write a row.
drop policy if exists "llm calls are readable by their owner" on public.llm_calls;
create policy "llm calls are readable by their owner" on public.llm_calls
  for select using (auth.uid() = user_id);

-- Free-tier abuse control. ai_usage in schema.sql counts actions per day; this
-- counts money, which is what actually needs a ceiling once one student can
-- hold a conversation rather than press a button.
create table if not exists public.credit_ledger (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users on delete cascade,
  delta      numeric(10,4) not null,       -- + granted, - spent
  reason     text not null,
  ref        text,
  created_at timestamptz not null default now()
);

create index if not exists credit_ledger_user_idx
  on public.credit_ledger (user_id, created_at desc);

alter table public.credit_ledger enable row level security;

drop policy if exists "credit ledger is readable by its owner" on public.credit_ledger;
create policy "credit ledger is readable by its owner" on public.credit_ledger
  for select using (auth.uid() = user_id);

-- ===========================================================================
-- Session start, atomically
--
-- Two tabs pressing Start on the same topic must not open two sessions: the
-- turn counter is the only thing standing between a stuck student and an
-- unbounded bill, and it does not work if there are two of it.
-- ===========================================================================
create or replace function public.start_learning_session(
  p_topic_ref text,
  p_concept_ref text
)
returns public.learning_sessions
language plpgsql
security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_row public.learning_sessions;
begin
  if v_user is null then
    raise exception 'not signed in';
  end if;

  select * into v_row
    from public.learning_sessions
   where user_id = v_user
     and topic_ref = p_topic_ref
     and status = 'active'
   order by started_at desc
   limit 1
   for update;

  if found then
    return v_row;
  end if;

  insert into public.learning_sessions (user_id, topic_ref, concept_ref)
  values (v_user, p_topic_ref, p_concept_ref)
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.start_learning_session(text, text) from public;
grant execute on function public.start_learning_session(text, text) to authenticated;



-- ===========================================================================
-- compliance.sql
-- ===========================================================================

-- PaperPath — consent, retention and safety
--
-- Run after schema.sql and tutor.sql.
--
-- ---------------------------------------------------------------------------
-- WHY THIS FILE EXISTS BEFORE THE PRODUCT DOES
--
-- Almost every user of this app is a child, and India's Digital Personal Data
-- Protection Act treats a child's data as a separate category with its own
-- rules: verifiable parental consent before processing, no behavioural
-- advertising or tracking of children at all, and a real route for a parent to
-- see and delete what has been collected.
--
-- Consent is also the one thing that cannot be added later. It has to be
-- recorded at the moment it is given, against the policy version the parent
-- actually read, with evidence of how it was verified — and none of that can be
-- reconstructed six months afterwards from a signup date. A product that ships
-- first and adds consent later has no lawful basis for the data it already
-- holds, and its only honest fix is to delete it.
--
-- So: DOB at signup, account locked until a parent consents, one row per
-- purpose, and a purge job that runs whether or not anyone remembers it.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- Who the account holder is
-- ---------------------------------------------------------------------------

-- An actual date of birth, not an age band. The band is what we show; the date
-- is what an audit needs, and it is also the only way to know when a student
-- turns 18 and the parental consent stops being required.
alter table public.profiles add column if not exists dob date;

-- is_minor is NOT a column, and the first attempt at one is worth recording.
--
-- It was a stored generated column over (dob > current_date - 18 years).
-- Postgres refuses that outright — a generated expression must be IMMUTABLE —
-- and it is right to: a value computed once at write time would still say
-- "minor" the morning the student turns eighteen, and would go on saying it
-- for ever.
--
-- So age is derived at read time, from dob, by the function below and by
-- isMinorFromDob() in lib/consent/age.ts. Two implementations of one rule is
-- a smell; they exist because PostgREST cannot select a function as a column,
-- and the app needs the answer in TypeScript while the policies need it in
-- SQL. Change one, change both.
create or replace function public.is_minor(p_dob date)
returns boolean
language sql
stable
as $$
  -- Unknown date of birth counts as a minor. The population is overwhelmingly
  -- under 18, and the cost of guessing wrong in the other direction is
  -- processing a child's data with no lawful basis.
  select p_dob is null or p_dob > (current_date - interval '18 years');
$$;

grant execute on function public.is_minor(date) to authenticated;

-- pending_consent | active | read_only | suspended
--
-- read_only is the state after a parent withdraws consent. The account is not
-- deleted — a withdrawal is not a deletion request, and treating it as one
-- destroys a student's work over a checkbox — but nothing new is processed.
alter table public.profiles
  add column if not exists account_state text not null default 'pending_consent';

alter table public.profiles
  add column if not exists role text not null default 'student';   -- student | parent

-- Which language the tutor teaches in: hinglish | hi-IN | en-IN.
--
-- The column existed on `subjects` from the first migration and was read into
-- the prompt as a bare string that nothing acted on — a student set to hi-IN
-- got the same Hinglish as everyone else. It belongs on the profile, because
-- it is a property of the reader and not of the syllabus.
alter table public.profiles
  add column if not exists language text not null default 'hinglish';

-- ---------------------------------------------------------------------------
-- WHICH COLUMNS A STUDENT MAY WRITE
--
-- schema.sql gives profiles one policy: `for all using (auth.uid() = id)`.
-- Row-level, which is what it says on the tin — and it means a signed-in
-- student could UPDATE ANY COLUMN of their own row straight from the browser.
--
-- Including account_state. Setting that to 'active' skips the parental consent
-- gate completely. Including dob, which decides whether consent is required at
-- all. Including role, and plan.
--
-- The generated is_minor column was written to stop exactly this and never
-- could have: a student who can write dob can declare themselves an adult, and
-- the derived column would faithfully agree.
--
-- RLS has no column granularity, so the fix is a GRANT. Revoke the blanket
-- update and hand back only the three fields that are genuinely the student's:
-- their name, and the language they want to be taught in.
--
-- Everything else is written by the server with the service-role key. That is
-- the distinction that was missing.
-- ---------------------------------------------------------------------------
revoke update on public.profiles from authenticated;
grant update (first_name, last_name, language) on public.profiles to authenticated;

-- ---------------------------------------------------------------------------
-- Email on the profile
--
-- auth.users has it, and the admin API can list users — but only a page at a
-- time. Looking a student up by email through auth.admin.listUsers() finds the
-- first fifty accounts and silently misses everyone else, which is invisible
-- in development and breaks the moment a school imports a roster of 200.
--
-- So it is denormalised here, kept in step by the trigger below, and every
-- lookup by email goes through this column with a real index behind it.
-- ---------------------------------------------------------------------------
alter table public.profiles add column if not exists email text;

create unique index if not exists profiles_email_idx
  on public.profiles (lower(email)) where email is not null;

-- Backfill anyone who signed up before this column existed.
update public.profiles p
   set email = u.email
  from auth.users u
 where u.id = p.id and p.email is distinct from u.email;

-- Replaces the trigger function in schema.sql, carrying the email across as
-- well as the name. Safe to re-run; schema.sql can be re-run after this
-- without losing it only if this file is run again, so run them in order.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, first_name, last_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'first_name',
             split_part(coalesce(new.raw_user_meta_data ->> 'full_name', ''), ' ', 1),
             ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', '')
  )
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

-- An email change in auth has to reach the profile, or a lookup finds the old
-- address for ever.
create or replace function public.sync_profile_email()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  update public.profiles set email = new.email where id = new.id;
  return new;
end;
$$;

drop trigger if exists on_auth_user_email_changed on auth.users;
create trigger on_auth_user_email_changed
  after update of email on auth.users
  for each row execute function public.sync_profile_email();

-- ---------------------------------------------------------------------------
-- Consent
--
-- One row per purpose, per grant. Rows are never updated in place and never
-- deleted: a withdrawal sets withdrawn_at, so the history of what was
-- permitted when is intact. That history is the entire evidentiary value of
-- the table.
-- ---------------------------------------------------------------------------
create table if not exists public.consents (
  id             uuid primary key default gen_random_uuid(),
  student_id     uuid not null references auth.users on delete cascade,
  parent_id      uuid references auth.users on delete set null,
  -- account | ai_processing | voice | analytics
  --
  -- There is deliberately no 'marketing' purpose for a minor. Under the DPDP
  -- Act, behavioural advertising and tracking of children is prohibited
  -- outright — so the safe design is not an unticked box, it is the absence of
  -- the box.
  purpose        text not null,
  granted        boolean not null,
  -- parent_otp | parent_payment | school_authority | self_adult
  method         text not null,
  -- Which privacy policy the parent actually saw. A consent recorded against
  -- "the privacy policy" means nothing once the policy changes.
  policy_version text not null,
  evidence       jsonb not null default '{}'::jsonb,   -- {otp_ref, txn_id, ...}
  ip             inet,
  user_agent     text,
  granted_at     timestamptz not null default now(),
  withdrawn_at   timestamptz
);

create index if not exists consents_student_idx
  on public.consents (student_id, purpose, granted_at desc);

alter table public.consents enable row level security;

-- Both sides may read; neither may write. Consent rows are written by the
-- server after it has verified the OTP, because a row a client can insert is
-- not evidence of anything.
drop policy if exists "consent is visible to both sides" on public.consents;
create policy "consent is visible to both sides" on public.consents
  for select using (auth.uid() = student_id or auth.uid() = parent_id);

-- Current state of one purpose: the newest row wins, and a withdrawn row does
-- not count however recently it was granted.
create or replace function public.has_consent(p_student uuid, p_purpose text)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select coalesce(
    (select c.granted and c.withdrawn_at is null
       from public.consents c
      where c.student_id = p_student and c.purpose = p_purpose
      order by c.granted_at desc
      limit 1),
    false
  );
$$;

grant execute on function public.has_consent(uuid, text) to authenticated;

-- ---------------------------------------------------------------------------
-- OTP challenges
--
-- How a parent proves they are the parent. The DPDP Act asks for VERIFIABLE
-- consent, and a checkbox on the child's own screen verifies nothing — the
-- child ticks it.
--
-- Only a hash is stored. A support engineer reading the table must not be able
-- to complete a consent, and an exported backup must not be a list of live
-- codes.
-- ---------------------------------------------------------------------------
create table if not exists public.otp_challenges (
  id           uuid primary key default gen_random_uuid(),
  -- Who the code is about, not who receives it.
  student_id   uuid not null references auth.users on delete cascade,
  purpose      text not null default 'parent_consent',
  phone        text not null,
  code_hash    text not null,
  attempts     int  not null default 0,
  -- Five minutes. Long enough for an SMS on a bad network, short enough that a
  -- code seen over a shoulder is useless by the time it is typed.
  expires_at   timestamptz not null default (now() + interval '5 minutes'),
  consumed_at  timestamptz,
  created_at   timestamptz not null default now()
);

create index if not exists otp_challenges_student_idx
  on public.otp_challenges (student_id, created_at desc);

alter table public.otp_challenges enable row level security;
-- No policy: written and read only by the server with the service-role key.

-- ---------------------------------------------------------------------------
-- Voice
--
-- Recordings are the most sensitive thing this app could hold — a child's
-- voice, identifiable, in their own home. So: separate consent purpose,
-- private storage, and a 30-day life whatever else happens. The transcript
-- survives; the audio does not.
-- ---------------------------------------------------------------------------
create table if not exists public.voice_blobs (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users on delete cascade,
  session_id  uuid references public.learning_sessions on delete set null,
  storage_path text not null,
  duration_ms int,
  transcript  text,
  created_at  timestamptz not null default now()
);

create index if not exists voice_blobs_created_idx on public.voice_blobs (created_at);

alter table public.voice_blobs enable row level security;

drop policy if exists "voice is self-service" on public.voice_blobs;
create policy "voice is self-service" on public.voice_blobs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('voice-notes', 'voice-notes', false)
on conflict (id) do nothing;

drop policy if exists "own voice: read" on storage.objects;
create policy "own voice: read" on storage.objects
  for select using (
    bucket_id = 'voice-notes'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "own voice: write" on storage.objects;
create policy "own voice: write" on storage.objects
  for insert with check (
    bucket_id = 'voice-notes'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- ---------------------------------------------------------------------------
-- Erasure requests
--
-- A parent asking for deletion gets an immediate stop and a scheduled hard
-- delete, not an instant one: a mis-tapped button should be recoverable for a
-- few days, and there are records (payment, tax) that cannot lawfully go at
-- all. Soft first, hard on a timer, with the reason for anything retained
-- written down.
-- ---------------------------------------------------------------------------
create table if not exists public.erasure_requests (
  id            uuid primary key default gen_random_uuid(),
  student_id    uuid not null references auth.users on delete cascade,
  requested_by  uuid references auth.users on delete set null,
  scope         text not null default 'all',    -- all | transcripts | voice
  status        text not null default 'pending', -- pending | done | refused
  -- What is kept and why. Empty means everything went.
  retained_note text,
  requested_at  timestamptz not null default now(),
  -- 30 days. Long enough to undo a mistake, short enough to be a real promise.
  execute_after timestamptz not null default (now() + interval '30 days'),
  completed_at  timestamptz
);

alter table public.erasure_requests enable row level security;

drop policy if exists "erasure requests are visible to the student" on public.erasure_requests;
create policy "erasure requests are visible to the student" on public.erasure_requests
  for select using (auth.uid() = student_id or auth.uid() = requested_by);

-- ---------------------------------------------------------------------------
-- Retention
--
-- Point pg_cron at this nightly. Keeping a child's conversation for ever
-- because nobody wrote the delete is the most ordinary way to be
-- non-compliant.
--
-- Aggregates survive: mastery is a number about a student, not a record of
-- what they said, and deleting it would throw away the learning without
-- reducing anyone's exposure.
-- ---------------------------------------------------------------------------
create or replace function public.purge_expired_data()
returns table (what text, rows_removed bigint)
language plpgsql
security definer set search_path = public
as $$
declare
  v_turns bigint;
  v_flags bigint;
  v_calls bigint;
  v_erased bigint;
begin
  -- Conversation transcripts: 24 months.
  delete from public.session_turns where created_at < now() - interval '24 months';
  get diagnostics v_turns = row_count;

  -- Moderation flags: 12 months. A flag is about an incident, and an incident
  -- that has not mattered in a year should not follow a child around.
  delete from public.safety_flags
   where created_at < now() - interval '12 months' and status <> 'open';
  get diagnostics v_flags = row_count;

  -- Per-call model logs: 13 months, so a year-on-year cost comparison still
  -- works. These carry no student text — only counts.
  delete from public.llm_calls where created_at < now() - interval '13 months';
  get diagnostics v_calls = row_count;

  -- Voice: 30 days, and the row goes with it. The storage object is removed by
  -- the same job in scripts/purge-storage.ts — Postgres cannot reach the
  -- bucket, and a row deleted without its file is the worse of the two
  -- failures because nothing then points at the file to delete it.
  delete from public.voice_blobs where created_at < now() - interval '30 days';

  -- Spent and expired one-time codes. No reason to keep a hash of a code that
  -- can no longer be used.
  delete from public.otp_challenges
   where created_at < now() - interval '7 days';

  -- Closed rate-limit windows. Harmless to keep and pointless to; the table
  -- grows a row per subject per window otherwise.
  begin
    perform public.purge_rate_limits();
  exception when undefined_function then
    -- supabase/ratelimit.sql has not been run on this project. Not a reason to
    -- abort the retention job, which is the part that matters legally.
    null;
  end;

  -- Behavioural events, 13 months. No free text in them, but still per-student
  -- data about a child, and unbounded retention of that is the thing the rest
  -- of this file exists to prevent.
  begin
    perform public.purge_analytics();
  exception when undefined_function then
    null;
  end;

  -- Erasure requests that have matured.
  with due as (
    select student_id from public.erasure_requests
     where status = 'pending' and execute_after <= now()
  )
  delete from public.session_turns t using due where t.user_id = due.student_id;

  update public.erasure_requests
     set status = 'done', completed_at = now()
   where status = 'pending' and execute_after <= now();
  get diagnostics v_erased = row_count;

  return query
    select 'session_turns', v_turns
    union all select 'safety_flags', v_flags
    union all select 'llm_calls', v_calls
    union all select 'erasures_completed', v_erased;
end;
$$;

-- ---------------------------------------------------------------------------
-- Safety flags
--
-- Written by the gate in lib/safety/gate.ts. A student can never read this
-- table: someone who knows they were flagged learns how to phrase it so they
-- are not, and the self-harm path is the one where that matters most.
-- ---------------------------------------------------------------------------
create table if not exists public.safety_flags (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users on delete cascade,
  session_id uuid references public.learning_sessions on delete set null,
  -- self_harm | sexual | violence | harassment | injection | off_topic
  category   text not null,
  severity   text not null default 'review',   -- review | urgent
  -- Kept because a human has to be able to judge the flag. Purged at 12 months
  -- by purge_expired_data.
  excerpt    text,
  score      numeric(3,2),
  -- blocklist | classifier | output_check | parent_alert
  --
  -- parent_alert is a record of the escalation OUTPUT, not of an input that
  -- was flagged. It lives in the same table because the once-a-day guard in
  -- lib/safety/escalate.ts has to read it, and a separate table for one
  -- column would be a join nobody remembers to make.
  source     text not null,
  status     text not null default 'open',     -- open | actioned | dismissed
  handled_by uuid references auth.users on delete set null,
  handled_at timestamptz,
  -- What the reviewer concluded. Its own column rather than appended to the
  -- excerpt: what was said and what a reviewer made of it are different
  -- things, and overwriting the first with the second destroys the only
  -- evidence of why the decision was made.
  review_note text,
  created_at timestamptz not null default now()
);

alter table public.safety_flags add column if not exists review_note text;

create index if not exists safety_flags_open_idx
  on public.safety_flags (status, severity, created_at desc);

alter table public.safety_flags enable row level security;
-- No policy at all: server-side, service-role only, by design.

-- ---------------------------------------------------------------------------
-- Content drafts — the authoring pipeline
--
-- The model drafts, a human approves, and only then does anything reach the
-- curriculum tables. There is no publish path that skips the human, and the
-- absence of that path is the feature.
--
-- Published content is immutable; an edit is a new version. Sessions store the
-- version they were taught from, so editing a concept cannot rewrite what a
-- student was told last week.
-- ---------------------------------------------------------------------------
create table if not exists public.content_drafts (
  id           uuid primary key default gen_random_uuid(),
  entity_type  text not null check (entity_type in ('concept', 'question')),
  entity_id    text,                       -- null when it is new
  payload      jsonb not null,
  status       text not null default 'draft'
               check (status in ('draft', 'in_review', 'approved', 'published', 'rejected')),
  author_id    uuid references auth.users on delete set null,
  reviewer_id  uuid references auth.users on delete set null,
  review_notes text,
  -- 'human' | 'llm:<model>'. Needed to answer "how much of the curriculum was
  -- written by a model", which is a question schools do ask.
  generated_by text not null default 'human',
  -- What the validator said at draft time. A draft that failed validation
  -- never reaches in_review.
  issues       jsonb not null default '[]'::jsonb,
  version      int not null default 1,
  created_at   timestamptz not null default now(),
  published_at timestamptz
);

create index if not exists content_drafts_status_idx
  on public.content_drafts (status, entity_type, created_at desc);

alter table public.content_drafts enable row level security;
-- Internal tooling only; reached with the service-role key.

-- Which version of a concept a session was taught from.
alter table public.learning_sessions
  add column if not exists content_version int not null default 1;

-- Which prompt wrote a turn. Without this, a regression found next month
-- cannot be traced to the change that caused it.
alter table public.session_turns
  add column if not exists prompt_version text;

-- ---------------------------------------------------------------------------
-- Tutor speech
--
-- Synthesised audio of the tutor's own messages. NOT under a student folder and
-- NOT on the 30-day voice purge: this is our content read aloud, not a
-- recording of a child. Two students hearing the same worked example share one
-- file, which is what makes speech affordable at all — the tutor teaches from
-- a fixed content pack, so its sentences genuinely repeat.
--
-- Private anyway. A signed URL is short-lived and unguessable; a public bucket
-- would make every spoken explanation in the curriculum a scrapeable asset.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('tutor-audio', 'tutor-audio', false)
on conflict (id) do nothing;

-- Read only through the server's signed URLs. No client-side policy: the app
-- never lets a browser list or fetch from this bucket directly.



-- ===========================================================================
-- schools.sql
-- ===========================================================================

-- PaperPath — schools and coaching centres
--
-- Run after tutor.sql, and before billing.sql (can_access_chapter reads
-- org_members).
--
-- ---------------------------------------------------------------------------
-- WHY B2B IS A DIFFERENT SHAPE, NOT A BIGGER PLAN
--
-- A school does not buy a subscription per child; it buys seats, and it needs
-- one person to see forty students at once. That is a different access model
-- from anything else in this database: every other table answers "may this
-- user see their own row", and a teacher's whole job is seeing someone else's.
--
-- The temptation is to give teachers a broad RLS policy over student data.
-- That is how a leak happens — a teacher who leaves keeps the row, a section
-- that is deleted leaves the membership behind, and nobody notices because the
-- policy is written once and never read again.
--
-- So teachers get aggregates, computed by security-definer functions that
-- check the membership every time. A teacher can see that eleven students in
-- 8-A are stuck on additive inverse. They cannot read a session transcript,
-- and there is no endpoint that would let them.
-- ---------------------------------------------------------------------------

create table if not exists public.orgs (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  kind        text not null default 'school',   -- school | coaching
  plan        text not null default 'seats',
  seats       int  not null default 0,
  expires_at  date,
  created_at  timestamptz not null default now()
);

create table if not exists public.org_members (
  org_id   uuid not null references public.orgs on delete cascade,
  user_id  uuid not null references auth.users on delete cascade,
  role     text not null default 'student' check (role in ('student', 'teacher', 'admin')),
  joined_at timestamptz not null default now(),
  primary key (org_id, user_id)
);

create index if not exists org_members_user_idx on public.org_members (user_id);

create table if not exists public.sections (
  id         uuid primary key default gen_random_uuid(),
  org_id     uuid not null references public.orgs on delete cascade,
  name       text not null,                   -- 'Class 8-A'
  class_level int,
  teacher_id uuid references auth.users on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.section_students (
  section_id uuid not null references public.sections on delete cascade,
  student_id uuid not null references auth.users on delete cascade,
  primary key (section_id, student_id)
);

create index if not exists section_students_student_idx
  on public.section_students (student_id);

-- Assignments. A teacher setting a chapter with a deadline is the single most
-- requested B2B feature and the cheapest to build, because the tutor already
-- knows how to teach a topic — this only says which one and by when.
create table if not exists public.assignments (
  id          uuid primary key default gen_random_uuid(),
  section_id  uuid not null references public.sections on delete cascade,
  chapter_ref text references public.chapters on delete cascade,
  topic_ref   text references public.topics on delete cascade,
  due_on      date,
  note        text,
  created_by  uuid references auth.users on delete set null,
  created_at  timestamptz not null default now(),
  -- One or the other, never both and never neither.
  check ((chapter_ref is null) <> (topic_ref is null))
);

create index if not exists assignments_section_idx
  on public.assignments (section_id, due_on);

alter table public.orgs             enable row level security;
alter table public.org_members      enable row level security;
alter table public.sections         enable row level security;
alter table public.section_students enable row level security;
alter table public.assignments      enable row level security;

-- A member may see the org they belong to, and nothing else about it.
drop policy if exists "members can see their org" on public.orgs;
create policy "members can see their org" on public.orgs
  for select using (
    exists (select 1 from public.org_members m
             where m.org_id = orgs.id and m.user_id = auth.uid())
  );

drop policy if exists "members can see their own membership" on public.org_members;
create policy "members can see their own membership" on public.org_members
  for select using (user_id = auth.uid());

drop policy if exists "members can see sections in their org" on public.sections;
create policy "members can see sections in their org" on public.sections
  for select using (
    exists (select 1 from public.org_members m
             where m.org_id = sections.org_id and m.user_id = auth.uid())
  );

-- A student sees which sections they are in. A teacher does NOT read the
-- roster through this table — that goes through the function below, which
-- checks they still teach the section at the moment they ask.
drop policy if exists "students can see their own enrolment" on public.section_students;
create policy "students can see their own enrolment" on public.section_students
  for select using (student_id = auth.uid());

drop policy if exists "students see assignments set for them" on public.assignments;
create policy "students see assignments set for them" on public.assignments
  for select using (
    exists (select 1 from public.section_students ss
             where ss.section_id = assignments.section_id and ss.student_id = auth.uid())
    or exists (select 1 from public.sections s
                where s.id = assignments.section_id and s.teacher_id = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- Is this caller the teacher of this section?
--
-- Every function below starts here. Written once so the check cannot be
-- forgotten in the fourth one somebody adds.
-- ---------------------------------------------------------------------------
create or replace function public.teaches_section(p_section uuid)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1
      from public.sections s
      join public.org_members m on m.org_id = s.org_id and m.user_id = auth.uid()
     where s.id = p_section
       and (s.teacher_id = auth.uid() or m.role = 'admin')
  );
$$;

-- ---------------------------------------------------------------------------
-- Class overview — one row per student, red/amber/green
-- ---------------------------------------------------------------------------
create or replace function public.section_overview(p_section uuid)
returns table (
  student_id  uuid,
  name        text,
  avg_score   numeric,
  topics_done int,
  last_active timestamptz,
  state       text
)
language plpgsql
stable
security definer set search_path = public
as $$
begin
  if not public.teaches_section(p_section) then
    raise exception 'not your section';
  end if;

  return query
  select
    ss.student_id,
    coalesce(p.first_name, 'Student') as name,
    round(coalesce(avg(m.score), 0), 0) as avg_score,
    count(*) filter (where m.score >= 65)::int as topics_done,
    max(s.updated_at) as last_active,
    case
      -- Inactive beats weak. A student who has not opened the app in a week
      -- is the one a teacher needs to speak to first, whatever their score.
      when max(s.updated_at) is null
        or max(s.updated_at) < now() - interval '7 days' then 'red'
      when coalesce(avg(m.score), 0) < 40 then 'red'
      when coalesce(avg(m.score), 0) < 65 then 'amber'
      else 'green'
    end as state
  from public.section_students ss
  left join public.profiles p on p.id = ss.student_id
  left join public.topic_mastery m on m.user_id = ss.student_id
  left join public.learning_sessions s on s.user_id = ss.student_id
  where ss.section_id = p_section
  group by ss.student_id, p.first_name
  order by avg_score asc;
end;
$$;

-- ---------------------------------------------------------------------------
-- Topic heatmap — where the whole class is stuck
--
-- The most valuable screen for a teacher, because it is actionable tomorrow
-- morning: it names the topic to reteach to the room rather than the students
-- to worry about.
-- ---------------------------------------------------------------------------
create or replace function public.section_heatmap(p_section uuid)
returns table (
  topic_ref   text,
  title       text,
  class_avg   numeric,
  struggling  int,
  attempted   int,
  -- The misconception the most students in this class actually hold. This is
  -- the line that turns a heatmap into a lesson plan.
  top_misconception text
)
language plpgsql
stable
security definer set search_path = public
as $$
begin
  if not public.teaches_section(p_section) then
    raise exception 'not your section';
  end if;

  return query
  select
    t.id,
    t.title,
    round(avg(m.score), 0) as class_avg,
    count(*) filter (where m.score < 40)::int as struggling,
    count(*)::int as attempted,
    (
      select e.misconception_id
        from public.error_events e
        join public.section_students ss2 on ss2.student_id = e.user_id
       where ss2.section_id = p_section
         and e.topic_ref = t.id
         and e.misconception_id is not null
         and e.created_at > now() - interval '30 days'
       group by e.misconception_id
       order by count(distinct e.user_id) desc
       limit 1
    ) as top_misconception
  from public.section_students ss
  join public.topic_mastery m on m.user_id = ss.student_id
  join public.topics t on t.id = m.topic_ref
  where ss.section_id = p_section
  group by t.id, t.title
  order by class_avg asc;
end;
$$;

grant execute on function public.teaches_section(uuid) to authenticated;
grant execute on function public.section_overview(uuid) to authenticated;
grant execute on function public.section_heatmap(uuid) to authenticated;

-- Seats in use, so an admin can see what they are paying for.
create or replace view public.org_seat_usage as
  select o.id as org_id, o.name, o.seats,
         count(*) filter (where m.role = 'student') as students_enrolled
    from public.orgs o
    left join public.org_members m on m.org_id = o.id
   group by o.id, o.name, o.seats;



-- ===========================================================================
-- billing.sql
-- ===========================================================================

-- PaperPath — subscriptions
--
-- Run after tutor.sql.
--
-- ---------------------------------------------------------------------------
-- THE WEBHOOK IS THE TRUTH, NOT THE BROWSER
--
-- Razorpay's checkout hands the browser a success callback. Access must never
-- be granted from it. It fires before the payment has settled, it does not
-- fire at all when the student closes the tab on a successful payment, and it
-- is a fetch call a fourteen-year-old can make by hand.
--
-- So every state change below is written by the webhook handler and by nothing
-- else. The browser's callback does one thing: show a spinner until this table
-- says otherwise.
--
-- ---------------------------------------------------------------------------
-- WHY THERE IS A DUNNING STATE AND NOT JUST 'ACTIVE'
--
-- UPI autopay is the only subscription rail that works at scale in India —
-- card penetration in this market is low and cards fail more often than the
-- mandate does. But mandate execution still fails 15-20% of the time in any
-- given month: insufficient balance on the day, a bank outage, an app that did
-- not surface the notification.
--
-- Revoking access the moment a charge fails treats an ordinary bank hiccup as
-- a cancellation, and roughly doubles churn against a three-day grace period.
-- Hence `past_due` with `grace_until`: the student keeps studying, the parent
-- gets a message, and access only stops if nobody acts.
-- ---------------------------------------------------------------------------

create table if not exists public.subscriptions (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references auth.users on delete cascade,
  -- Null for a whole-account plan; set when a subscription buys one subject.
  subject_ref         text references public.subjects on delete set null,

  provider            text not null default 'razorpay',
  provider_sub_id     text unique,
  provider_plan_id    text,

  plan                text not null,          -- monthly | annual
  amount_inr          numeric(10,2) not null,
  -- upi_autopay | card | netbanking. Recorded because renewal success differs
  -- enormously between them and an averaged number hides that.
  method              text,

  -- created  → mandate not yet authorised
  -- active   → paid, access granted
  -- past_due → a charge failed; access continues until grace_until
  -- halted   → grace expired or the mandate was revoked; access stopped
  -- cancelled/expired → ended normally
  status              text not null default 'created',

  current_period_end  timestamptz,
  grace_until         timestamptz,
  dunning_attempts    int not null default 0,

  cancelled_at        timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists subscriptions_user_idx
  on public.subscriptions (user_id, status);

create index if not exists subscriptions_dunning_idx
  on public.subscriptions (status, grace_until)
  where status = 'past_due';

alter table public.subscriptions enable row level security;

-- Readable by its owner, writable by the webhook only.
drop policy if exists "subscriptions are readable by their owner" on public.subscriptions;
create policy "subscriptions are readable by their owner" on public.subscriptions
  for select using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Webhook events
--
-- Providers retry, and they retry the ones that succeeded slowly as well as
-- the ones that failed. Without a uniqueness constraint on the event id, one
-- retry of subscription.charged extends a subscription by a second month for
-- free.
-- ---------------------------------------------------------------------------
create table if not exists public.billing_events (
  id            uuid primary key default gen_random_uuid(),
  provider      text not null default 'razorpay',
  provider_event_id text not null,
  event         text not null,
  payload       jsonb not null,
  processed_at  timestamptz,
  error         text,
  created_at    timestamptz not null default now(),
  unique (provider, provider_event_id)
);

alter table public.billing_events enable row level security;
-- Server-side only.

-- ---------------------------------------------------------------------------
-- Invoices
--
-- Ed-tech SaaS is taxable at 18% GST under SAC 999293. The invoice number
-- series must be gapless and per financial year, which is why it comes from a
-- sequence taken inside the insert rather than from a count.
-- ---------------------------------------------------------------------------
create table if not exists public.invoices (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users on delete cascade,
  subscription_id uuid references public.subscriptions on delete set null,

  -- PP/2026-27/000123
  number         text not null unique,
  financial_year text not null,

  -- Base + tax, stored separately because the parent's receipt has to show
  -- both and recomputing tax from a total introduces rounding drift.
  base_inr       numeric(10,2) not null,
  gst_inr        numeric(10,2) not null,
  total_inr      numeric(10,2) not null,
  gst_rate       numeric(5,2) not null default 18.00,
  sac_code       text not null default '999293',

  provider_payment_id text,
  issued_at      timestamptz not null default now()
);

create index if not exists invoices_user_idx on public.invoices (user_id, issued_at desc);

alter table public.invoices enable row level security;

drop policy if exists "invoices are readable by their owner" on public.invoices;
create policy "invoices are readable by their owner" on public.invoices
  for select using (auth.uid() = user_id);

create sequence if not exists public.invoice_seq;

-- India's financial year runs April to March, so an invoice raised in March
-- and one raised in April belong to different series.
create or replace function public.financial_year(at timestamptz default now())
returns text
language sql
immutable
as $$
  select case
    when extract(month from at) >= 4
      then to_char(at, 'YYYY') || '-' || to_char(at + interval '1 year', 'YY')
    else to_char(at - interval '1 year', 'YYYY') || '-' || to_char(at, 'YY')
  end;
$$;

create or replace function public.issue_invoice(
  p_user uuid,
  p_subscription uuid,
  p_total_inr numeric,
  p_payment_id text
)
returns public.invoices
language plpgsql
security definer set search_path = public
as $$
declare
  v_row public.invoices;
  v_fy text := public.financial_year();
  v_base numeric(10,2);
  v_gst numeric(10,2);
begin
  -- The amount charged is inclusive of GST — that is what the parent agreed
  -- to pay — so tax is extracted from it rather than added to it.
  v_base := round(p_total_inr / 1.18, 2);
  v_gst  := round(p_total_inr - v_base, 2);

  insert into public.invoices (
    user_id, subscription_id, number, financial_year,
    base_inr, gst_inr, total_inr, provider_payment_id
  )
  values (
    p_user, p_subscription,
    'PP/' || v_fy || '/' || lpad(nextval('public.invoice_seq')::text, 6, '0'),
    v_fy, v_base, v_gst, p_total_inr, p_payment_id
  )
  returning * into v_row;

  return v_row;
end;
$$;

-- ---------------------------------------------------------------------------
-- What a student may open
--
-- One function, used by every gate, so "is this paid for" has exactly one
-- answer in the codebase.
--
-- Free access is the first chapter of a subject, whole. Not a trial period and
-- not three questions: a parent cannot judge teaching from a countdown, and
-- one complete chapter is the smallest honest sample.
-- ---------------------------------------------------------------------------
create or replace function public.can_access_chapter(p_user uuid, p_chapter text)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select
    coalesce((select c.is_free from public.chapters c where c.id = p_chapter), false)
    or exists (
      select 1
        from public.subscriptions s
        left join public.chapters c on c.id = p_chapter
       where s.user_id = p_user
         and (s.subject_ref is null or s.subject_ref = c.subject_ref)
         and (
           s.status = 'active'
           -- A failed charge inside its grace window still opens the app.
           or (s.status = 'past_due' and s.grace_until > now())
         )
    )
    -- A school seat covers everything for as long as the seat is paid for.
    or exists (
      select 1
        from public.org_members m
        join public.orgs o on o.id = m.org_id
       where m.user_id = p_user
         and o.expires_at >= current_date
    );
$$;

grant execute on function public.can_access_chapter(uuid, text) to authenticated;



-- ===========================================================================
-- ratelimit.sql
-- ===========================================================================

-- PaperPath — rate limiting
--
-- Run after compliance.sql.
--
-- ---------------------------------------------------------------------------
-- WHY THIS IS NOT ENOUGH ON ITS OWN, AND WHY IT IS STILL WORTH HAVING
--
-- ai_usage in schema.sql already caps what one ACCOUNT can spend in a day.
-- That is the important limit and it holds. What it does not stop is someone
-- creating accounts: sign up, burn the free tutor turns, sign up again. The
-- per-account limit is per account, and accounts are free.
--
-- So this adds a second axis — the caller's IP — to the endpoints that cost
-- money before an account has proved anything: signing up, asking for a
-- consent code, and the first few tutor turns.
--
-- An IP is a blunt instrument in India. A school, a housing society or a
-- mobile carrier's CGNAT can put hundreds of genuine students behind one
-- address, so the limits below are deliberately loose: they are shaped to stop
-- a script, not to ration a computer lab. Anything tighter would break the
-- exact customer we most want.
--
-- ---------------------------------------------------------------------------
-- WHY POSTGRES AND NOT REDIS
--
-- The app is serverless, so an in-memory counter is per-instance and therefore
-- not a limit at all. Redis would be the textbook answer and is a second piece
-- of infrastructure to run, pay for and monitor for a product with no users
-- yet. The database is already there, already has connection pooling, and a
-- counter row per window is a cheap write.
--
-- Revisit when the write volume justifies it. The interface in
-- lib/ratelimit.ts does not change when the store does.
-- ---------------------------------------------------------------------------

create table if not exists public.rate_limits (
  -- The bucket: 'consent_request', 'signup', 'tutor_turn'.
  action     text not null,
  -- The subject: an IP, or a user id where the limit is per account.
  subject    text not null,
  -- Start of the fixed window this row counts.
  --
  -- A fixed window lets twice the limit through across a boundary, which a
  -- sliding window would not. That is an acceptable trade here: the limits are
  -- loose by design, and a sliding window costs a row per request instead of a
  -- row per window.
  window_start timestamptz not null,
  count      int not null default 0,
  primary key (action, subject, window_start)
);

-- Old windows are dead weight. Indexed so the sweep below is cheap.
create index if not exists rate_limits_window_idx on public.rate_limits (window_start);

alter table public.rate_limits enable row level security;
-- No policy: written only by the function below, which runs as definer.

-- ---------------------------------------------------------------------------
-- Take one slot
--
-- Check and increment in one statement, holding the row. Two round trips from
-- the app is racy in exactly the case that matters — a script firing requests
-- in parallel is the thing being limited, and it would read "under the limit"
-- on all of them at once.
-- ---------------------------------------------------------------------------
create or replace function public.take_rate_limit(
  p_action text,
  p_subject text,
  p_limit int,
  p_window_seconds int
)
returns table (allowed boolean, used int, resets_at timestamptz)
language plpgsql
security definer set search_path = public
as $$
declare
  v_start timestamptz;
  v_count int;
begin
  -- Floor the current time to the window, so every caller in the same window
  -- lands on the same row without needing to agree on anything.
  v_start := to_timestamp(
    floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds
  );

  insert into public.rate_limits (action, subject, window_start, count)
  values (p_action, p_subject, v_start, 1)
  on conflict (action, subject, window_start)
    do update set count = public.rate_limits.count + 1
  returning public.rate_limits.count into v_count;

  return query
    select v_count <= p_limit, v_count, v_start + make_interval(secs => p_window_seconds);
end;
$$;

revoke all on function public.take_rate_limit(text, text, int, int) from public;
-- anon as well as authenticated: the sign-up and consent paths are reached
-- before there is a session.
grant execute on function public.take_rate_limit(text, text, int, int) to anon, authenticated;

-- Housekeeping. Called by purge_expired_data via the daily cron.
create or replace function public.purge_rate_limits()
returns int
language plpgsql
security definer set search_path = public
as $$
declare
  v_count int;
begin
  delete from public.rate_limits where window_start < now() - interval '2 days';
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;



-- ===========================================================================
-- analytics.sql
-- ===========================================================================

-- PaperPath — the built-in event store
--
-- Run after compliance.sql.
--
-- ---------------------------------------------------------------------------
-- WHY THE APP COLLECTS ITS OWN EVENTS
--
-- The alternative was an analytics SDK, and for this product that is a bad
-- trade: a dependency, a script on the client, and — with most vendors —
-- third-party cookies on pages used by children, which is the exact thing the
-- consent design exists to avoid.
--
-- The four numbers that say whether the thing is working (cost per student,
-- verdict parse failures, the share of diagnoses coming from a model, p95
-- first-token latency) are all answerable from Postgres. So they are.
--
-- NEXT_PUBLIC_ANALYTICS_URL can still point somewhere else. This is the
-- default so that an unconfigured deployment can still tell it is broken,
-- which was the previous state's real failing.
--
-- ---------------------------------------------------------------------------
-- WHAT MAY NEVER GO IN HERE
--
-- No message text, no answers, no names, no phone numbers. lib/analytics
-- rejects property names that look like free text, and this table is the
-- reason that check is worth having: it is the one store whose whole purpose
-- is being queried in bulk later by someone who was not there when it was
-- written.
-- ---------------------------------------------------------------------------

create table if not exists public.analytics_events (
  id         bigserial primary key,
  event      text not null,
  -- Nullable on purpose: client-side UI events arrive without one, and an
  -- event that cannot be tied to a person is the better default.
  user_id    uuid references auth.users on delete set null,
  properties jsonb not null default '{}'::jsonb,
  at         timestamptz not null default now()
);

create index if not exists analytics_events_at_idx on public.analytics_events (at desc);
create index if not exists analytics_events_name_idx on public.analytics_events (event, at desc);

alter table public.analytics_events enable row level security;
-- No policy. Written by the collector with the service-role key, read by the
-- health dashboard the same way. A student can neither read nor write it.

-- ---------------------------------------------------------------------------
-- The four numbers, as one query
--
-- Written here rather than in the dashboard so that "cost per active student"
-- means one thing in the product and in any spreadsheet someone builds later.
-- ---------------------------------------------------------------------------
create or replace function public.health_snapshot(p_days int default 7)
returns jsonb
language plpgsql
stable
security definer set search_path = public
as $$
declare
  v_since timestamptz := now() - make_interval(days => p_days);
  v_cost numeric;
  v_students int;
  v_verdict_fail int;
  v_turns int;
  v_llm_diagnoses int;
  v_all_diagnoses int;
  v_p95 int;
  v_fallbacks int;
begin
  select coalesce(sum(cost_inr), 0), count(*) filter (where purpose in ('teach','check'))
    into v_cost, v_turns
    from public.llm_calls where created_at >= v_since;

  select count(distinct user_id) into v_students
    from public.learning_sessions where started_at >= v_since;

  select count(*) into v_verdict_fail
    from public.analytics_events
   where event = 'verdict_parse_failed' and at >= v_since;

  select count(*) into v_fallbacks
    from public.llm_calls where fell_back and created_at >= v_since;

  select count(*) filter (where source = 'llm'), count(*)
    into v_llm_diagnoses, v_all_diagnoses
    from public.error_events where created_at >= v_since;

  -- p95 first-token latency is not recorded directly; total call latency is
  -- the closest honest proxy and is labelled as such on the dashboard.
  select coalesce(
           percentile_disc(0.95) within group (order by latency_ms), 0
         )::int
    into v_p95
    from public.llm_calls
   where created_at >= v_since and purpose in ('teach','check') and latency_ms is not null;

  return jsonb_build_object(
    'days', p_days,
    'activeStudents', v_students,
    'costInr', round(v_cost, 2),
    'costPerStudentInr',
      case when v_students > 0 then round(v_cost / v_students, 2) else null end,
    'teachingTurns', v_turns,
    'verdictParseFailures', v_verdict_fail,
    'verdictFailureRate',
      case when v_turns > 0 then round(v_verdict_fail::numeric / v_turns, 4) else null end,
    'providerFallbacks', v_fallbacks,
    'diagnosesFromModel', v_llm_diagnoses,
    'diagnosesTotal', v_all_diagnoses,
    'modelDiagnosisShare',
      case when v_all_diagnoses > 0
        then round(v_llm_diagnoses::numeric / v_all_diagnoses, 4) else null end,
    'p95LatencyMs', v_p95
  );
end;
$$;

revoke all on function public.health_snapshot(int) from public;

-- ---------------------------------------------------------------------------
-- Activation
--
-- The one number. lib/analytics/events.ts has defined it since the taxonomy
-- was written and nothing computed it, which made "design onboarding backwards
-- from activation" advice nobody could act on.
--
--   A student is activated when they reach the Developing band (40+) on at
--   least one topic within 48 hours of signing up.
--
-- Why that definition: below 40 a student has watched a lesson; above it they
-- have been taught a topic AND shown they can do the ordinary questions on it.
-- And 48 hours because the students who come back on day three are almost
-- entirely the ones who felt the thing work on day one.
--
-- Reported as a cohort so it can be read as a trend. A single lifetime number
-- goes up and to the right whatever happens and tells nobody anything.
-- ---------------------------------------------------------------------------
create or replace function public.activation_by_cohort(p_weeks int default 8)
returns table (
  cohort_week date,
  signed_up   int,
  activated   int,
  rate        numeric
)
language sql
stable
security definer set search_path = public
as $$
  with cohorts as (
    select
      u.id,
      date_trunc('week', u.created_at)::date as week,
      u.created_at
    from auth.users u
    where u.created_at >= now() - make_interval(weeks => p_weeks)
  ),
  first_hit as (
    select
      c.id,
      c.week,
      min(m.updated_at) filter (where m.score >= 40) as reached_at,
      c.created_at
    from cohorts c
    left join public.topic_mastery m on m.user_id = c.id
    group by c.id, c.week, c.created_at
  )
  select
    week as cohort_week,
    count(*)::int as signed_up,
    count(*) filter (
      where reached_at is not null
        and reached_at <= created_at + interval '48 hours'
    )::int as activated,
    round(
      count(*) filter (
        where reached_at is not null
          and reached_at <= created_at + interval '48 hours'
      )::numeric / nullif(count(*), 0),
      3
    ) as rate
  from first_hit
  group by week
  order by week desc;
$$;

revoke all on function public.activation_by_cohort(int) from public;

-- ---------------------------------------------------------------------------
-- Retention for the event store
--
-- Flagged in docs/legal-review.md and not implemented at the time. The table
-- holds no free text — property names matching message/content/answer/name/
-- phone/email/transcript/excerpt are rejected at both the client and the
-- collector — but it is still per-student behavioural data, and behavioural
-- data about children with no expiry is exactly what the rest of this schema
-- exists to avoid.
--
-- 13 months, matching llm_calls, so a year-on-year comparison still works.
-- ---------------------------------------------------------------------------
create or replace function public.purge_analytics()
returns int
language plpgsql
security definer set search_path = public
as $$
declare
  v_count int;
begin
  delete from public.analytics_events where at < now() - interval '13 months';
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- ---------------------------------------------------------------------------
-- Errors, when nothing else is collecting them
--
-- lib/observability.ts posts to ERROR_REPORT_URL when one is set and falls back
-- to this table when it is not. That fallback is the point: before it, every
-- failure path called console.error and stopped, which on a serverless host is
-- a line nobody reads, rotated out in a week. The first sign a route was 500ing
-- was a student saying so — and students do not say so, they close the tab.
--
-- Carries no student text. lib/observability.ts drops context keys matching
-- message/content/answer/name/phone/email/transcript/excerpt/body/prompt, and
-- anything longer than 120 characters, because a catch block is exactly where
-- someone attaches a student's words without thinking about it.
-- ---------------------------------------------------------------------------
create table if not exists public.error_reports (
  id         bigserial primary key,
  where_     text not null,
  kind       text,
  message    text,
  stack      text,
  context    jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- PostgREST maps the column name directly, and `where` is reserved — hence the
-- trailing underscore in the column and the alias below, so the app can insert
-- `where` and read `where` without either side knowing.
create or replace view public.error_reports_view as
  select id, where_ as where, kind, message, stack, context, created_at
    from public.error_reports;

create index if not exists error_reports_at_idx on public.error_reports (created_at desc);
create index if not exists error_reports_where_idx on public.error_reports (where_, created_at desc);

alter table public.error_reports enable row level security;
-- No policy. Written and read with the service-role key only.

create or replace function public.purge_error_reports()
returns int
language plpgsql
security definer set search_path = public
as $$
declare
  v_count int;
begin
  -- 90 days. Long enough to see a pattern, short enough that a stack trace
  -- naming an internal path does not sit around for a year.
  delete from public.error_reports where created_at < now() - interval '90 days';
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;



-- ===========================================================================
-- tenancy.sql
-- ===========================================================================

-- PaperPath — multi-tenancy
--
-- Run after schools.sql (it extends org_members) and after tutor.sql (it adds
-- a column to every curriculum table).
--
-- ---------------------------------------------------------------------------
-- WHAT CHANGED, AND WHY IT COULD NOT WAIT
--
-- Everything before this file assumed one curriculum, owned by whoever runs
-- the deployment: `subjects` and its children had no owner, and the read
-- policy was literally `using (true)`.
--
-- That is correct for a product you run yourself. It is wrong for a product
-- you SELL, where a coaching institute buys the platform and uploads their own
-- material — because their material must not be visible to another institute's
-- students, and their admin must be able to publish without being in the
-- vendor's environment file.
--
-- Tenant isolation is the one thing that genuinely cannot be retrofitted
-- comfortably. Every table, every query and every policy has to be touched,
-- and a single missed one leaks one customer's content to another — silently,
-- until a customer finds it. So it goes in before the curriculum grows.
--
-- ---------------------------------------------------------------------------
-- THE SHAPE: org_id IS NULL MEANS SHARED
--
--   org_id IS NULL   base curriculum, written by the vendor, visible to
--                    everyone. This is the product being sold.
--   org_id = <uuid>  written by that org, visible only to its members.
--
-- A nullable column rather than two tables, because a topic is a topic and the
-- tutor should not care who wrote it. The cost is that every query has to
-- remember the NULL case; the alternative was duplicating five tables and
-- every join through them.
--
-- ---------------------------------------------------------------------------
-- THE TRAP THIS FILE CANNOT CLOSE ON ITS OWN
--
-- Row-level security does not apply to the service-role key, and the server
-- reads the question bank with it — it has to, because the answers are
-- readable by nobody else. So RLS protects the browser and NOT the server.
--
-- Every service-role read of curriculum must scope by org in code. That is
-- lib/tenancy.ts, and scripts/verify-rls.ts checks the browser half. The
-- server half is checked by scripts/audit-flows.ts and by reading the diff.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- Who owns a piece of curriculum
-- ---------------------------------------------------------------------------
alter table public.subjects       add column if not exists org_id uuid references public.orgs on delete cascade;
alter table public.chapters       add column if not exists org_id uuid references public.orgs on delete cascade;
alter table public.topics         add column if not exists org_id uuid references public.orgs on delete cascade;
alter table public.concepts       add column if not exists org_id uuid references public.orgs on delete cascade;
alter table public.bank_questions add column if not exists org_id uuid references public.orgs on delete cascade;

-- Every read filters on this, so it is indexed. Partial on NOT NULL because
-- the shared rows are the common case and a NULL index entry earns nothing.
create index if not exists subjects_org_idx       on public.subjects (org_id)       where org_id is not null;
create index if not exists chapters_org_idx       on public.chapters (org_id)       where org_id is not null;
create index if not exists topics_org_idx         on public.topics (org_id)         where org_id is not null;
create index if not exists concepts_org_idx       on public.concepts (org_id)       where org_id is not null;
create index if not exists bank_questions_org_idx on public.bank_questions (org_id) where org_id is not null;

-- ---------------------------------------------------------------------------
-- Which orgs the caller belongs to
--
-- One function, used by every policy below, so "which content can this person
-- see" has exactly one definition. A policy that inlines its own version is a
-- policy that will disagree with the others after the third edit.
-- ---------------------------------------------------------------------------
create or replace function public.my_org_ids()
returns uuid[]
language sql
stable
security definer set search_path = public
as $$
  select coalesce(array_agg(m.org_id), '{}'::uuid[])
    from public.org_members m
   where m.user_id = auth.uid();
$$;

grant execute on function public.my_org_ids() to authenticated;

-- The rule itself, so the policies below read as one line each.
create or replace function public.can_see_content(p_org uuid)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select p_org is null or p_org = any(public.my_org_ids());
$$;

grant execute on function public.can_see_content(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- The read policies, rewritten
--
-- These were `using (true)`. That was right when there was one curriculum and
-- is a cross-tenant leak the moment there are two.
-- ---------------------------------------------------------------------------
drop policy if exists "subjects are readable" on public.subjects;
create policy "subjects are readable" on public.subjects
  for select to authenticated using (public.can_see_content(org_id));

drop policy if exists "chapters are readable" on public.chapters;
create policy "chapters are readable" on public.chapters
  for select to authenticated using (public.can_see_content(org_id));

drop policy if exists "topics are readable" on public.topics;
create policy "topics are readable" on public.topics
  for select to authenticated using (public.can_see_content(org_id));

drop policy if exists "concepts are readable" on public.concepts;
create policy "concepts are readable" on public.concepts
  for select to authenticated using (public.can_see_content(org_id));

-- bank_questions still has NO select policy. Answers are unreachable from a
-- browser regardless of tenancy, and that has not changed.

-- ---------------------------------------------------------------------------
-- Roles inside an org
--
-- schools.sql allowed student | teacher | admin. 'admin' there meant "can see
-- every section in this org", which is a teaching-side power. The buyer needs
-- more than that: publishing curriculum, managing seats, adding teachers.
--
-- Renamed to org_admin so it cannot be confused with the vendor's own admin —
-- which is deliberately NOT a database role at all. ADMIN_EMAILS stays what it
-- is: a super-admin is a person in the vendor's environment file, unreachable
-- from inside the database, because they can change what every student in
-- every org is taught.
-- ---------------------------------------------------------------------------
alter table public.org_members drop constraint if exists org_members_role_check;

alter table public.org_members
  add constraint org_members_role_check
  check (role in ('student', 'teacher', 'org_admin'));

update public.org_members set role = 'org_admin' where role = 'admin';

create or replace function public.is_org_admin(p_org uuid)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.org_members m
     where m.org_id = p_org
       and m.user_id = auth.uid()
       and m.role = 'org_admin'
  );
$$;

grant execute on function public.is_org_admin(uuid) to authenticated;

-- teaches_section referenced role = 'admin'. Kept working under the new name.
create or replace function public.teaches_section(p_section uuid)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1
      from public.sections s
      join public.org_members m on m.org_id = s.org_id and m.user_id = auth.uid()
     where s.id = p_section
       and (s.teacher_id = auth.uid() or m.role = 'org_admin')
  );
$$;

-- ---------------------------------------------------------------------------
-- Content drafts belong to an org too
--
-- Without this, one institute's content team sees another's unpublished
-- material in the review queue — which is worse than seeing the published
-- version, because a draft is what they are still arguing about internally.
-- ---------------------------------------------------------------------------
alter table public.content_drafts
  add column if not exists org_id uuid references public.orgs on delete cascade;

create index if not exists content_drafts_org_idx
  on public.content_drafts (org_id, status);

-- ---------------------------------------------------------------------------
-- Licences
--
-- orgs already had plan, seats and expires_at from schools.sql — enough to
-- gate access, not enough to bill. Both revenue paths run side by side: an
-- institute buys a licence and its students pay nothing, and a parent who
-- found the app directly still subscribes. can_access_chapter already reads
-- both, so nothing downstream changes.
-- ---------------------------------------------------------------------------
alter table public.orgs add column if not exists licence_inr numeric(10,2);
alter table public.orgs add column if not exists licence_starts_on date;
alter table public.orgs add column if not exists billing_email text;
alter table public.orgs add column if not exists billing_contact text;

-- Whether this org may publish its own curriculum at all. Some plans are
-- "use the vendor's content on your students" and nothing more, and that is a
-- commercial line rather than a technical one — so it is a column, not an
-- assumption baked into the console.
alter table public.orgs
  add column if not exists can_author boolean not null default false;

-- ---------------------------------------------------------------------------
-- Analytics stops knowing who anybody is
--
-- analytics_events.user_id was written on every event and read by no query.
-- health_snapshot counts distinct students from learning_sessions;
-- activation_by_cohort works off auth.users and topic_mastery. Neither has
-- ever touched this column.
--
-- Meanwhile the browser collector took the id off the session cookie and
-- stored it without checking the 'analytics' consent at all — so a parent who
-- declined it had their child's behaviour recorded anyway, and the box on the
-- consent screen was asking permission for something that happened either
-- way.
--
-- Dropping the column is what makes removing that box honest. What is left is
-- a count of how often each event happened, which is all anything ever read.
-- Existing rows lose the id with it, which is the point: data collected for a
-- purpose that did not exist should not survive the discovery that it did not
-- exist.
-- ---------------------------------------------------------------------------
alter table public.analytics_events drop column if exists user_id;

-- Is this licence in force today?
--
-- Both ends, not just the far one. A licence sold in March to start in June is
-- a normal thing for a school — the academic year begins when it begins — and
-- checking only expires_at would hand over three months of access that nobody
-- has paid for yet. Null start means "already running", which is what every
-- org created before this column existed means.
--
-- One function rather than the same date arithmetic in four places, because
-- the two branches of can_access_chapter disagreeing about what "live" means
-- is a bug that only shows up on the boundary day.
-- stable, not immutable: it reads current_date. Marking a function immutable
-- when it depends on the clock is what produced the 42P17 rejection on
-- is_minor, and where Postgres accepts it instead of rejecting it the result
-- gets folded into a cached plan and the licence stops expiring.
create or replace function public.licence_is_live(p_starts date, p_expires date)
returns boolean
language sql
stable
as $$
  select (p_starts is null or p_starts <= current_date)
     and (p_expires is null or p_expires >= current_date);
$$;

-- ---------------------------------------------------------------------------
-- Access, extended
--
-- An org's own chapter is readable by its members without any subscription:
-- they have already paid, through the licence. The base curriculum still
-- follows is_free plus a subscription plus a seat, exactly as before.
-- ---------------------------------------------------------------------------
create or replace function public.can_access_chapter(p_user uuid, p_chapter text)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select
    -- The org's own material, to its own members with a live licence.
    exists (
      select 1
        from public.chapters c
        join public.org_members m on m.org_id = c.org_id
        join public.orgs o on o.id = c.org_id
       where c.id = p_chapter
         and c.org_id is not null
         and m.user_id = p_user
         and public.licence_is_live(o.licence_starts_on, o.expires_at)
    )
    -- The free chapter of the base curriculum.
    or coalesce(
      (select c.is_free from public.chapters c
        where c.id = p_chapter and c.org_id is null),
      false)
    -- A direct subscription.
    or exists (
      select 1
        from public.subscriptions s
        left join public.chapters c on c.id = p_chapter
       where s.user_id = p_user
         and (s.subject_ref is null or s.subject_ref = c.subject_ref)
         and (
           s.status = 'active'
           or (s.status = 'past_due' and s.grace_until > now())
         )
    )
    -- A seat at an institute with a live licence covers the base curriculum.
    or exists (
      select 1
        from public.org_members m
        join public.orgs o on o.id = m.org_id
       where m.user_id = p_user
         and public.licence_is_live(o.licence_starts_on, o.expires_at)
    );
$$;

grant execute on function public.can_access_chapter(uuid, text) to authenticated;
