/* Concatenates the migrations into supabase/all.sql, in dependency order.
 *
 *   npm run db:bundle
 *
 * ---------------------------------------------------------------------------
 * WHY ONE FILE
 *
 * The order matters and nothing enforces it. compliance.sql replaces the
 * trigger function schema.sql installs; billing.sql's can_access_chapter
 * references org_members, which schools.sql creates. Out of order, none of
 * that errors loudly — the app boots, most of it works, and the parts that do
 * not fail weeks later in ways that look like application bugs. A missing
 * email trigger surfaces as "the roster import cannot find anyone".
 *
 * Six pastes into the Supabase SQL editor is six chances to get that wrong,
 * and the person doing it is usually doing it once, quickly, at the end of
 * something else. So: one paste.
 *
 * ---------------------------------------------------------------------------
 * WHAT IS DELIBERATELY LEFT OUT
 *
 * schema.sql, because it is the pre-existing app's and may already be applied.
 *
 * cron.sql, because it schedules a job against a URL and a secret that have to
 * be filled in by hand. A scheduler pointing at REPLACE-ME is worse than no
 * scheduler: it looks configured.
 *
 * ---------------------------------------------------------------------------
 * THE GENERATED FILE IS NOT THE SOURCE
 *
 * Edit the individual migrations and regenerate. Editing all.sql directly
 * leaves the two disagreeing, and nobody can then tell which one ran. */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));

/* Dependency order, not alphabetical. Each entry says what breaks if it runs
   too early, because that is the only thing anyone needs to know before
   reordering this list. */
const ORDER: { file: string; needs: string }[] = [
  { file: "tutor.sql", needs: "schema.sql — adds columns to its `attempts` table" },
  { file: "compliance.sql", needs: "schema.sql for profiles, tutor.sql for the retention job's tables" },
  { file: "schools.sql", needs: "tutor.sql for topics and topic_mastery" },
  { file: "billing.sql", needs: "schools.sql — can_access_chapter reads org_members" },
  { file: "ratelimit.sql", needs: "nothing, but compliance.sql's purge calls into it" },
  { file: "analytics.sql", needs: "tutor.sql for llm_calls and error_events" },
  {
    file: "tenancy.sql",
    needs:
      "schools.sql (extends org_members) and billing.sql (replaces can_access_chapter) — LAST, because it rewrites what came before",
  },
];

function main() {
  const parts: string[] = [
    "-- PaperPath — every migration after schema.sql, in one file.",
    "--",
    "-- GENERATED by scripts/build-migration.ts. Do not edit: edit the source files",
    "-- and regenerate, or the two will disagree and nobody will be able to tell",
    "-- which one is running on the database.",
    "--",
    "-- RUN supabase/schema.sql FIRST if you have not. This assumes profiles,",
    "-- attempts and ai_usage already exist.",
    "--",
    "-- cron.sql is NOT here: it schedules against a URL and a secret you have to",
    "-- fill in by hand, and a scheduler pointing at REPLACE-ME looks configured.",
    "--",
    "-- Order below is dependency order, not alphabetical:",
    ...ORDER.map((entry) => `--   ${entry.file.padEnd(16)} needs ${entry.needs}`),
    "",
  ];

  for (const { file } of ORDER) {
    parts.push(
      "",
      "",
      "-- ===========================================================================",
      `-- ${file}`,
      "-- ===========================================================================",
      "",
      readFileSync(resolve(ROOT, "supabase", file), "utf8"),
    );
  }

  const out = parts.join("\n");
  writeFileSync(resolve(ROOT, "supabase/all.sql"), out, "utf8");

  console.log(
    `supabase/all.sql — ${Math.round(out.length / 1024)} KB, ${out.split("\n").length} lines, ${ORDER.length} migrations`,
  );
  console.log("\nPaste it into the Supabase SQL editor, then: npm run db:check");
}

main();
